# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/95f5e946-81cf-4f80-8776-3f7458803ab7";
      fsType = "ext4";
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/75BB-53A3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  fileSystems."/mnt/hoth-jellyfin" = {
    device = "//192.168.40.183/jellyfin";
    fsType = "cifs";
    options = [
      "credentials=${config.sops.templates.\"smb/passwords/ferrix-smb\".path}"
      "x-systemd.automount"
      "noauto"
      "nofail"
      "x-systemd.idle-timeout=5min"
      "x-systemd.device-timeout=10s"
      "x-systemd.mount-timeout=10s"
      "vers=3.1.1"
      "uid=mpfammatter"
      "gid=users"
      "file_mode=0644"
      "dir_mode=0755"
    ];
  };
  fileSystems."/mnt/hoth-pinchflat" = {
    device = "//192.168.40.183/pinchflat";
    fsType = "cifs";
    options = [
      "credentials=${config.sops.templates.\"smb/passwords/ferrix-smb\".path}"
      "x-systemd.automount"
      "noauto"
      "nofail"
      "x-systemd.idle-timeout=5min"
      "x-systemd.device-timeout=10s"
      "x-systemd.mount-timeout=10s"
      "vers=3.1.1"
      "uid=mpfammatter"
      "gid=users"
      "file_mode=0644"
      "dir_mode=0755"
    ];
  };
  swapDevices = [ ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}